version: '3.8'

services:
  api:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gold
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gold
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
