version: "3.9"
services:
  db:
    image: postgres:16
    container_name: quantia-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  web:
    build:
      context: .
    container_name: quantia-web
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=quantia;Username=postgres;Password=root

volumes:
  pgdata:
