apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
  namespace: quantia
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/pa-2025-upgraded-ajout-api-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/gold
            - name: OPENAI_API_KEY
            - name: REDDIT_CLIENT_ID
            - name: REDDIT_CLIENT_SECRET
          image: jobordeau/api:latest
          name: api
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
